### ISSUE TITLE
json input file from Android Chromium browser, wrong file structure

### ISSUE THREAD

**Issue by Guybrush3pw00d** [radam9/bookmarks-converter#191]
My best regards. I've been using Adblock browser (a Chromium browser for Android) for long and I wanted to export its bookmarks. Unfortunately, it has the feature disabled unlike other Chromium browsers available for Android (one ot the reasons behind the switch) so I've manually saved the bookmarks file ([bookmarks_unedited.json](https://github.com/radam9/bookmarks-converter/files/15189152/bookmarks_unedited.jjson)).
It clearly seems to me a json but bookmarks-converter doesn't accept it as valid. I've then checked the expected file structure [here ](https://github.com/radam9/bookmarks-converter/blob/main/bookmarks_file_structure.md) and have found out that it isn't the same so I've tried to edit the original file obtaining [bookmarks.json](https://github.com/radam9/bookmarks-converter/files/15189129/bookmarks.json) but it still complains.
I've then found [this](https://rongjiecomputer.github.io/chrome/bookmark-recovery/#windows ) javascript (thanks to one of the advices given [here](https://stackoverflow.com/questions/34050058/convert-json-formatted-chrome-bookmark-file-into-html)) which has worked like a charm solving my problem but I'd still like to understand what I'm doing wrong here, clearly not an issue with bookmarks-converter itself and I care about underlining it.
Thanks in advance and have a nice day!! :)

**Comment by radam9** [comment]
Hey @Guybrush3pw00d 
The modified version you have upload `bookmarks.json` doesn't fully follow the standard chrome bookmarks syntax.
I tried to download `bookmarks_unedited.json` to check which errors you are getting, but I can't download that one.

If you could re-upload that file, I could check what the problem is for you.
or if you could provide what kind of errors you are getting I could try to walk you through what the problem is.

**Comment by Guybrush3pw00d** [comment]
First of all, thanks for your kind follow-up and apologies for not replying before. I don't know how it could happen, given that everything has gone fine with no errors but I've just reuploaded the [bookmarks_unedited.json](https://github.com/radam9/bookmarks-converter/files/15222743/bookmarks_unedited.json). It is the file as taken from AdBlock browser and it is even worse than the version edited by me as it contains much more attributes not adehering the the structure in the docs. 
It's clear it isn't just that, probably there is also something deeper in the json given that just removing those extra attributes as I've already done wasn't enough.
Thanks again and have a nice day. :)

**Comment by radam9** [comment]
@Guybrush3pw00d, there was a small bug due to the `meta_info` field.
I fixed that and released a new version, now it should work as intended with the original file you extracted from your browser.

**Comment by Guybrush3pw00d** [comment]
First of all thanks for your effort and please accept my sincere apologies for not coming back before with a confirmation. The reason was that I've tried quite promptly but I was getting the same outcome but before reporting I've choosen to refresh my environment to be on the safe side and avoid making a false report. This has taken time and I couldn't before. I can confirm that everything works like a charm. Thanks, really a lot! :)
