### ISSUE TITLE
Feature request: specify output file

### ISSUE THREAD

**Issue by redjax** [radam9/bookmarks-converter#209]
When calling `bookmarks_converter`, allow an option like `--output-path` or `--output-file`, where a file name/path can be specified. Optionally, strip the file extension from the file path and append `.html`, `.json`, `.db` where appropriate.

**Comment by radam9** [comment]
Hey @redjax 
Currently working on an update, will add this to the list.

**Comment by redjax** [comment]
Thanks! This utility is great, I found it while working on something similar as a pet project. What you have here is exactly what I'm looking for, just missing the output option :)

I'll see if I can figure it out and get a PR in for you, but I'm not the best dev out there so... I wouldn't wait on me 😂

**Comment by radam9** [comment]
@redjax , don't waste your time on a PR, I am doing a small re-write so it will not be compatible with it.

**Comment by radam9** [comment]
added in #210

**Comment by GitHubitual** [comment]
Curious if this code supports keep tags and keywords in the bookmarks as a separate line under the URL?

**Comment by radam9** [comment]
> Curious if this code supports keeping tags and keywords in the bookmarks as a separate line under the URL?

you can find the supported output formats and it's contents here [bookmarks_file_structure.md](https://github.com/radam9/bookmarks-converter/blob/88fc8f9ba0d252c6d0617dc06632054c6b0373fb/bookmarks_file_structure.md)
