### ISSUE TITLE
Adding support for Safari Bookmarks

### ISSUE THREAD

**Issue by tomy0000000** [radam9/bookmarks-converter#71]
I'm interested in helping adding support for safari bookmarks.

I have done some research, and here's what I know so far:

* The default location that safari store bookmarks on macOS is `~/Library/Safari/Bookmarks.plist` ([ref](https://apple.stackexchange.com/a/401560/373272))
* The file is packed with Apple's binary property list format, which can be breakdown following [this awesome guide](https://medium.com/@karaiskc/understanding-apples-binary-property-list-format-281e6da00dbd)
* Luckily, we also have [plistlib](https://docs.python.org/3/library/plistlib.html) which should be very helpful for parsing the file

Seeing the code, I found that there seems to be a well-organized structure of how this library is orchestrated between different components/classes. I was hoping if there are some manual to guide me on steps to add support for this.

Thank you

**Comment by radam9** [comment]
Hey Tomy, 
Thanks for you interest in the project.
I have no problem adding support for safari bookmarks, but we can add the support though the `.html` file from the safari export feature rather than binary file.
That is what is currently done for Chrome and Firefox.
Firefox stores its bookmarks in a sqlite3 database file, but I do not parse that I only parse the exported `.html` or `.json` files.

**Comment by tomy0000000** [comment]
If I'm not getting it wrong, the currently-supported chrome json format is what chrome access directly.
What I'm trying to achieve here is allowing the library to export the parsed bookmarks to the same binary plist format that Safari expected.
If that went well, we'll be able to explicitly import bookmarks into Safari without messing around with the GUI.

**Comment by radam9** [comment]
The chrome json format is only used as an import, and that is because it is similar to the firefox json export file and the custom json file the library exports.
If you have a proper HTML Bookmarks export file from chrome, firefox, safari or the one exported from this library, you use that to import your bookmarks to safari.
That is the recommended way to import your bookmarks in general for all browsers.

**Comment by tomy0000000** [comment]
Sorry, but I don't think you understand my point here. Let me try to elaborate in another way.

Since I have been using different browser across different platform/devices, so I've been manually migrating bookmarks from Chrome to Safari quite often for a long time.

Therefore, it'll be best if I could accomplish this task automatically, or do it with a single command/click, at the very least. That means I don't want to actually fire up Safari, go to bookmark page, click import, and locate the chrome-exported HTML bookmarks, but by directly overwriting `~/Library/Safari/Bookmarks.plist` file.

I know this might not be the common practice, but I'm experimenting.

Anyway, I'll try modified on my fork without interfering your project, but I am hoping you can guide me on where should this be implemented if so.

**Comment by radam9** [comment]
1) If you cannot use any of the models in the `models.py`, you will have to create a new model.
2) you will need to create a `Mixin` class for the `.plist` functionality. you need 3 main methods `parse_plist`, `convert_to_plist` and `save_to_plist`.
3) you add the format `"plist"` to the `_formats` tuple in the `BookmarksConverter` class
4) add the plist entries in `cli.py` for CLI support.

With `db`, `html` and `json` the package functions as follows:
1. The bookmarks are parsed by the `parse_` method and the resulting bookmarks are stored in the `_tree` attribute.
2. The `_tree` attribute will contain the bookmarks as a hierarchy (in the form of one of the models in `models.py`).
3. Then the files are converted to the required format using the `convert_to_` method.
4. Finally the bookmarks are saved into the output file using the `save_to_` method.

**Comment by tomy0000000** [comment]
Thanks for the comprehensive guide, will submit a PR if you're interested in merging.
